const REQUEST_SUCCESSFUL = 200;

const INVALID_DATA_ERROR = 400;

const NOT_FOUND_ERROR = 404;

const DEFAULT_ERROR = 500;

module.exports = {
  REQUEST_SUCCESSFUL,
  INVALID_DATA_ERROR,
  NOT_FOUND_ERROR,
  DEFAULT_ERROR,
};
